// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/service.proto

package jp.co.cyberagent.stf.input.agent.proto;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code jp.co.cyberagent.stf.input.agent.proto.ServiceAction}
   */
  public enum ServiceAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNLOCK = 1;</code>
     */
    UNLOCK(0, 1),
    /**
     * <code>WAKE_LOCK_ACQUIRE = 2;</code>
     */
    WAKE_LOCK_ACQUIRE(1, 2),
    /**
     * <code>WAKE_LOCK_RELEASE = 3;</code>
     */
    WAKE_LOCK_RELEASE(2, 3),
    /**
     * <code>IDENTITY = 4;</code>
     */
    IDENTITY(3, 4),
    ;

    /**
     * <code>UNLOCK = 1;</code>
     */
    public static final int UNLOCK_VALUE = 1;
    /**
     * <code>WAKE_LOCK_ACQUIRE = 2;</code>
     */
    public static final int WAKE_LOCK_ACQUIRE_VALUE = 2;
    /**
     * <code>WAKE_LOCK_RELEASE = 3;</code>
     */
    public static final int WAKE_LOCK_RELEASE_VALUE = 3;
    /**
     * <code>IDENTITY = 4;</code>
     */
    public static final int IDENTITY_VALUE = 4;


    public final int getNumber() { return value; }

    public static ServiceAction valueOf(int value) {
      switch (value) {
        case 1: return UNLOCK;
        case 2: return WAKE_LOCK_ACQUIRE;
        case 3: return WAKE_LOCK_RELEASE;
        case 4: return IDENTITY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServiceAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ServiceAction>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceAction>() {
            public ServiceAction findValueByNumber(int number) {
              return ServiceAction.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServiceAction[] VALUES = values();

    public static ServiceAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ServiceAction(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jp.co.cyberagent.stf.input.agent.proto.ServiceAction)
  }

  public interface ServiceCallOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;
    /**
     * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
     */
    jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction getAction();

    // optional bytes message = 2;
    /**
     * <code>optional bytes message = 2;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional bytes message = 2;</code>
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code jp.co.cyberagent.stf.input.agent.proto.ServiceCall}
   */
  public static final class ServiceCall extends
      com.google.protobuf.GeneratedMessage
      implements ServiceCallOrBuilder {
    // Use ServiceCall.newBuilder() to construct.
    private ServiceCall(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServiceCall(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServiceCall defaultInstance;
    public static ServiceCall getDefaultInstance() {
      return defaultInstance;
    }

    public ServiceCall getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceCall(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction value = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall.class, jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall.Builder.class);
    }

    public static com.google.protobuf.Parser<ServiceCall> PARSER =
        new com.google.protobuf.AbstractParser<ServiceCall>() {
      public ServiceCall parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceCall(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceCall> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction action_;
    /**
     * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
     */
    public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction getAction() {
      return action_;
    }

    // optional bytes message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>optional bytes message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes message = 2;</code>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private void initFields() {
      action_ = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.UNLOCK;
      message_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jp.co.cyberagent.stf.input.agent.proto.ServiceCall}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall.class, jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall.Builder.class);
      }

      // Construct using jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        action_ = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.UNLOCK;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_descriptor;
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall getDefaultInstanceForType() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall.getDefaultInstance();
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall build() {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall buildPartial() {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall result = new jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall) {
          return mergeFrom((jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall other) {
        if (other == jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceCall) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;
      private jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction action_ = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.UNLOCK;
      /**
       * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
       */
      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction getAction() {
        return action_;
      }
      /**
       * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
       */
      public Builder setAction(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.UNLOCK;
        onChanged();
        return this;
      }

      // optional bytes message = 2;
      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes message = 2;</code>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>optional bytes message = 2;</code>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jp.co.cyberagent.stf.input.agent.proto.ServiceCall)
    }

    static {
      defaultInstance = new ServiceCall(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jp.co.cyberagent.stf.input.agent.proto.ServiceCall)
  }

  public interface IdentityServiceCallOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string serial = 1;
    /**
     * <code>required string serial = 1;</code>
     */
    boolean hasSerial();
    /**
     * <code>required string serial = 1;</code>
     */
    java.lang.String getSerial();
    /**
     * <code>required string serial = 1;</code>
     */
    com.google.protobuf.ByteString
        getSerialBytes();
  }
  /**
   * Protobuf type {@code jp.co.cyberagent.stf.input.agent.proto.IdentityServiceCall}
   */
  public static final class IdentityServiceCall extends
      com.google.protobuf.GeneratedMessage
      implements IdentityServiceCallOrBuilder {
    // Use IdentityServiceCall.newBuilder() to construct.
    private IdentityServiceCall(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IdentityServiceCall(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IdentityServiceCall defaultInstance;
    public static IdentityServiceCall getDefaultInstance() {
      return defaultInstance;
    }

    public IdentityServiceCall getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IdentityServiceCall(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serial_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall.class, jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall.Builder.class);
    }

    public static com.google.protobuf.Parser<IdentityServiceCall> PARSER =
        new com.google.protobuf.AbstractParser<IdentityServiceCall>() {
      public IdentityServiceCall parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IdentityServiceCall(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IdentityServiceCall> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string serial = 1;
    public static final int SERIAL_FIELD_NUMBER = 1;
    private java.lang.Object serial_;
    /**
     * <code>required string serial = 1;</code>
     */
    public boolean hasSerial() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serial = 1;</code>
     */
    public java.lang.String getSerial() {
      java.lang.Object ref = serial_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serial_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serial = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSerialBytes() {
      java.lang.Object ref = serial_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serial_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSerial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSerialBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSerialBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jp.co.cyberagent.stf.input.agent.proto.IdentityServiceCall}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall.class, jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall.Builder.class);
      }

      // Construct using jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serial_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_descriptor;
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall getDefaultInstanceForType() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall.getDefaultInstance();
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall build() {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall buildPartial() {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall result = new jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serial_ = serial_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall) {
          return mergeFrom((jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall other) {
        if (other == jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall.getDefaultInstance()) return this;
        if (other.hasSerial()) {
          bitField0_ |= 0x00000001;
          serial_ = other.serial_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSerial()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jp.co.cyberagent.stf.input.agent.proto.ServiceProto.IdentityServiceCall) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string serial = 1;
      private java.lang.Object serial_ = "";
      /**
       * <code>required string serial = 1;</code>
       */
      public boolean hasSerial() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serial = 1;</code>
       */
      public java.lang.String getSerial() {
        java.lang.Object ref = serial_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serial_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serial = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSerialBytes() {
        java.lang.Object ref = serial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serial = 1;</code>
       */
      public Builder setSerial(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serial = 1;</code>
       */
      public Builder clearSerial() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serial_ = getDefaultInstance().getSerial();
        onChanged();
        return this;
      }
      /**
       * <code>required string serial = 1;</code>
       */
      public Builder setSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serial_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jp.co.cyberagent.stf.input.agent.proto.IdentityServiceCall)
    }

    static {
      defaultInstance = new IdentityServiceCall(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jp.co.cyberagent.stf.input.agent.proto.IdentityServiceCall)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/service.proto\022&jp.co.cyberagent." +
      "stf.input.agent.proto\"e\n\013ServiceCall\022E\n\006" +
      "action\030\001 \002(\01625.jp.co.cyberagent.stf.inpu" +
      "t.agent.proto.ServiceAction\022\017\n\007message\030\002" +
      " \001(\014\"%\n\023IdentityServiceCall\022\016\n\006serial\030\001 " +
      "\002(\t*W\n\rServiceAction\022\n\n\006UNLOCK\020\001\022\025\n\021WAKE" +
      "_LOCK_ACQUIRE\020\002\022\025\n\021WAKE_LOCK_RELEASE\020\003\022\014" +
      "\n\010IDENTITY\020\004B\016B\014ServiceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceCall_descriptor,
              new java.lang.String[] { "Action", "Message", });
          internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jp_co_cyberagent_stf_input_agent_proto_IdentityServiceCall_descriptor,
              new java.lang.String[] { "Serial", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
