// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/service.proto

package jp.co.cyberagent.stf.input.agent.proto;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code jp.co.cyberagent.stf.input.agent.proto.ServiceAction}
   */
  public enum ServiceAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNLOCK = 0;</code>
     */
    UNLOCK(0, 0),
    /**
     * <code>LOCK = 1;</code>
     */
    LOCK(1, 1),
    /**
     * <code>ACQUIRE_WAKE_LOCK = 2;</code>
     */
    ACQUIRE_WAKE_LOCK(2, 2),
    /**
     * <code>RELEASE_WAKE_LOCK = 3;</code>
     */
    RELEASE_WAKE_LOCK(3, 3),
    /**
     * <code>GET_CLIPBOARD = 4;</code>
     */
    GET_CLIPBOARD(4, 4),
    /**
     * <code>GET_PHONENUMBER = 5;</code>
     */
    GET_PHONENUMBER(5, 5),
    /**
     * <code>GET_OPERATOR = 6;</code>
     */
    GET_OPERATOR(6, 6),
    /**
     * <code>GET_IMEI = 7;</code>
     */
    GET_IMEI(7, 7),
    /**
     * <code>SET_CLIPBOARD = 8;</code>
     */
    SET_CLIPBOARD(8, 8),
    /**
     * <code>SHOW_IDENTITY = 9;</code>
     */
    SHOW_IDENTITY(9, 9),
    ;

    /**
     * <code>UNLOCK = 0;</code>
     */
    public static final int UNLOCK_VALUE = 0;
    /**
     * <code>LOCK = 1;</code>
     */
    public static final int LOCK_VALUE = 1;
    /**
     * <code>ACQUIRE_WAKE_LOCK = 2;</code>
     */
    public static final int ACQUIRE_WAKE_LOCK_VALUE = 2;
    /**
     * <code>RELEASE_WAKE_LOCK = 3;</code>
     */
    public static final int RELEASE_WAKE_LOCK_VALUE = 3;
    /**
     * <code>GET_CLIPBOARD = 4;</code>
     */
    public static final int GET_CLIPBOARD_VALUE = 4;
    /**
     * <code>GET_PHONENUMBER = 5;</code>
     */
    public static final int GET_PHONENUMBER_VALUE = 5;
    /**
     * <code>GET_OPERATOR = 6;</code>
     */
    public static final int GET_OPERATOR_VALUE = 6;
    /**
     * <code>GET_IMEI = 7;</code>
     */
    public static final int GET_IMEI_VALUE = 7;
    /**
     * <code>SET_CLIPBOARD = 8;</code>
     */
    public static final int SET_CLIPBOARD_VALUE = 8;
    /**
     * <code>SHOW_IDENTITY = 9;</code>
     */
    public static final int SHOW_IDENTITY_VALUE = 9;


    public final int getNumber() { return value; }

    public static ServiceAction valueOf(int value) {
      switch (value) {
        case 0: return UNLOCK;
        case 1: return LOCK;
        case 2: return ACQUIRE_WAKE_LOCK;
        case 3: return RELEASE_WAKE_LOCK;
        case 4: return GET_CLIPBOARD;
        case 5: return GET_PHONENUMBER;
        case 6: return GET_OPERATOR;
        case 7: return GET_IMEI;
        case 8: return SET_CLIPBOARD;
        case 9: return SHOW_IDENTITY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServiceAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ServiceAction>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceAction>() {
            public ServiceAction findValueByNumber(int number) {
              return ServiceAction.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServiceAction[] VALUES = values();

    public static ServiceAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ServiceAction(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jp.co.cyberagent.stf.input.agent.proto.ServiceAction)
  }

  public interface ServiceRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;
    /**
     * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
     */
    jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction getAction();

    // optional string data = 2;
    /**
     * <code>optional string data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code jp.co.cyberagent.stf.input.agent.proto.ServiceRequest}
   */
  public static final class ServiceRequest extends
      com.google.protobuf.GeneratedMessage
      implements ServiceRequestOrBuilder {
    // Use ServiceRequest.newBuilder() to construct.
    private ServiceRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServiceRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServiceRequest defaultInstance;
    public static ServiceRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ServiceRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction value = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest.class, jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ServiceRequest> PARSER =
        new com.google.protobuf.AbstractParser<ServiceRequest>() {
      public ServiceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction action_;
    /**
     * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
     */
    public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction getAction() {
      return action_;
    }

    // optional string data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      action_ = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.UNLOCK;
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jp.co.cyberagent.stf.input.agent.proto.ServiceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest.class, jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest.Builder.class);
      }

      // Construct using jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        action_ = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.UNLOCK;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_descriptor;
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest getDefaultInstanceForType() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest.getDefaultInstance();
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest build() {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest buildPartial() {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest result = new jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest) {
          return mergeFrom((jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest other) {
        if (other == jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000002;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;
      private jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction action_ = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.UNLOCK;
      /**
       * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
       */
      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction getAction() {
        return action_;
      }
      /**
       * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
       */
      public Builder setAction(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .jp.co.cyberagent.stf.input.agent.proto.ServiceAction action = 1;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceAction.UNLOCK;
        onChanged();
        return this;
      }

      // optional string data = 2;
      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jp.co.cyberagent.stf.input.agent.proto.ServiceRequest)
    }

    static {
      defaultInstance = new ServiceRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jp.co.cyberagent.stf.input.agent.proto.ServiceRequest)
  }

  public interface ServiceResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool success = 1;
    /**
     * <code>required bool success = 1;</code>
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 1;</code>
     */
    boolean getSuccess();

    // optional string data = 2;
    /**
     * <code>optional string data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code jp.co.cyberagent.stf.input.agent.proto.ServiceResponse}
   */
  public static final class ServiceResponse extends
      com.google.protobuf.GeneratedMessage
      implements ServiceResponseOrBuilder {
    // Use ServiceResponse.newBuilder() to construct.
    private ServiceResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServiceResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServiceResponse defaultInstance;
    public static ServiceResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ServiceResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse.class, jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ServiceResponse> PARSER =
        new com.google.protobuf.AbstractParser<ServiceResponse>() {
      public ServiceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool success = 1;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>required bool success = 1;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    // optional string data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      success_ = false;
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jp.co.cyberagent.stf.input.agent.proto.ServiceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse.class, jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse.Builder.class);
      }

      // Construct using jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_descriptor;
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse getDefaultInstanceForType() {
        return jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse.getDefaultInstance();
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse build() {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse buildPartial() {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse result = new jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse) {
          return mergeFrom((jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse other) {
        if (other == jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000002;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jp.co.cyberagent.stf.input.agent.proto.ServiceProto.ServiceResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool success = 1;
      private boolean success_ ;
      /**
       * <code>required bool success = 1;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // optional string data = 2;
      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jp.co.cyberagent.stf.input.agent.proto.ServiceResponse)
    }

    static {
      defaultInstance = new ServiceResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jp.co.cyberagent.stf.input.agent.proto.ServiceResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/service.proto\022&jp.co.cyberagent." +
      "stf.input.agent.proto\"e\n\016ServiceRequest\022" +
      "E\n\006action\030\001 \002(\01625.jp.co.cyberagent.stf.i" +
      "nput.agent.proto.ServiceAction\022\014\n\004data\030\002" +
      " \001(\t\"0\n\017ServiceResponse\022\017\n\007success\030\001 \002(\010" +
      "\022\014\n\004data\030\002 \001(\t*\301\001\n\rServiceAction\022\n\n\006UNLO" +
      "CK\020\000\022\010\n\004LOCK\020\001\022\025\n\021ACQUIRE_WAKE_LOCK\020\002\022\025\n" +
      "\021RELEASE_WAKE_LOCK\020\003\022\021\n\rGET_CLIPBOARD\020\004\022" +
      "\023\n\017GET_PHONENUMBER\020\005\022\020\n\014GET_OPERATOR\020\006\022\014" +
      "\n\010GET_IMEI\020\007\022\021\n\rSET_CLIPBOARD\020\010\022\021\n\rSHOW_",
      "IDENTITY\020\tB\016B\014ServiceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceRequest_descriptor,
              new java.lang.String[] { "Action", "Data", });
          internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jp_co_cyberagent_stf_input_agent_proto_ServiceResponse_descriptor,
              new java.lang.String[] { "Success", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
